import { useEffect, useId, useRef, useState, type FormEvent } from "react";
import { IconArrowDown, IconArrowLeft, IconArrowRight, IconArrowUpRight, IconBrandWhatsapp, IconCheck, IconChevronDown, IconMenu2, IconX } from "@tabler/icons-react";
import { Link, useLocation, useNavigate, useParams } from "react-router";

type Locale = "ar" | "en";
type Copy = { ar: string; en: string };
type Product = {
  slug: string;
  name: Copy;
  short: Copy;
  description: Copy;
  tint: string;
  symbol: string;
  image: string;
  cardImage: string;
  sections: { title: Copy; text: Copy; image?: string }[];
  features: Copy[];
  featureDetails: Copy[];
  advantages: Copy[];
  screenshots: { label: Copy; src: string }[];
  pricing?: { name: Copy; price: string; oldPrice?: string; discount?: Copy; period: Copy; features: Copy[] }[];
};

const words = {
  nav: { products: { ar: "منتجاتنا", en: "Our Products" }, services: { ar: "الخدمات", en: "Our Services" }, about: { ar: "من نحن", en: "About us" }, clients: { ar: "عملاء نفخر بهم", en: "Clients" }, contact: { ar: "اتصل بنا", en: "Contact us" }, explore: { ar: "اكتشف منتجاتنا", en: "Browse apps" } },
  productsTitle: { ar: "تطبيقاتنا", en: "Apps" },
  productsIntro: { ar: "حلولنا البرمجية لإدارة الأساطيل ومحلات الخياطة والشيكات والأرشفة الإلكترونية.", en: "Business applications for fleet management, tailoring, financial checks, and electronic archiving." },
  servicesTitle: { ar: "خدماتنا", en: "Our Services" },
  aboutTitle: { ar: "من نحن", en: "About Us" },
  aboutText: { ar: "على مدى أكثر من 15 سنة تشرفنا بخدمة الكثير من العملاء في مختلف مجالات تخصصنا كبرمجة المواقع والاستضافة وحتى بناء أنظمة الإدارة والأرشفة الإلكترونية.", en: "Over the past 10 years, we have been honored to serve many clients in web programming, hosting, and building electronic management and archiving systems." },
  clientsTitle: { ar: "عملاء نفخر بهم", en: "Clients we are proud of" },
  contactTitle: { ar: "اتصل بنا", en: "Contact us" },
  contactText: { ar: "تواصل معنا للاستفسار عن خدماتنا وحلولنا.", en: "Get in touch to learn more about our services and solutions." },
  send: { ar: "إرسال", en: "Send Message" },
  success: { ar: "تم إرسال طلبك بنجاح.", en: "Your request has been submitted successfully." },
  demo: { ar: "طلب نسخة تجريبية (ديمو)", en: "Ask Demo Version" },
  more: { ar: "المزيد", en: "More" },
  featuresTitle: { ar: "المميزات", en: "Features" },
  advantagesTitle: { ar: "الخصائص", en: "Specialities" },
  screenshotsTitle: { ar: "لقطات من التطبيق", en: "Screenshots of the application" },
  pricingTitle: { ar: "الباقات والأسعار", en: "Packages and prices" },
  clients: { ar: "عملاء من قطاعات حكومية وخاصة نفخر بخدمتهم.", en: "Organizations across government and private sectors." },
  footer: { ar: "التكنولوجيا الماسية لتقنية المعلومات", en: "Diamond Technology Company" },
} satisfies Record<string, Copy | Record<string, Copy>>;

const products: Product[] = [
  {
    slug: "fleet", name: { ar: "أسطولي", en: "Ostoli" }, short: { ar: "إدارة الأسطول", en: "Fleet management" }, tint: "gold", symbol: "01",
    image: "/dt4it/products/fleet-banner.png", cardImage: "/dt4it/products/fleet-card.png",
    sections: [{ title: { ar: "كل أنواع المركبات", en: "All kinds of vehicles" }, text: { ar: "تابع أوامر التشغيل وسجلات الصيانة واستهلاك الوقود، وخزّن معلومات مركبات أسطولك واسترجعها بنقرة واحدة عبر تقارير شاملة، مع إمكانية استيراد بيانات السيارات من Excel.", en: "Track work orders, maintenance records, and fuel consumption. Store and retrieve vehicle information through comprehensive reports, and import vehicle data from Excel." }, image: "/dt4it/products/fleet-cars.png" }, { title: { ar: "السائقون", en: "Drivers" }, text: { ar: "استورد بيانات السائقين من Excel، وتلقّ تنبيهات عند قرب انتهاء رخص القيادة، واحتفظ بجميع مستندات السائقين في مكان واحد.", en: "Import driver data from Excel, receive alerts before licences expire, and keep all driver documents in one place." }, image: "/dt4it/products/fleet-drivers.png" }],
    description: { ar: "تطبيق أسطولي لإدارة أسطول السيارات والسائقين. استبدل جداول البيانات والورق بحل مركزي يسهل عمل مديري الأساطيل والسائقين والفنيين ومديري قطع الغيار.", en: "Fleet application to manage cars and drivers. Replace spreadsheets and paper with a centralized solution designed to make your work easier and give fleet managers, drivers, technicians, and parts managers the tools they need." },
    features: [{ ar: "إدارة الأسطول", en: "Fleet management" }, { ar: "صيانة الأسطول", en: "Fleet maintenance" }, { ar: "إدارة الوقود", en: "Fuel management" }, { ar: "إدارة المعدات", en: "Equipment management" }, { ar: "أوامر التشغيل", en: "Work orders" }, { ar: "قطع الغيار والمخازن", en: "Spare parts and stores" }, { ar: "الإشعارات", en: "Notifications" }, { ar: "التقارير", en: "Reports" }],
    featureDetails: [{ ar: "تتبع كل التفاصيل حول مركباتك ومعداتك من البداية إلى النهاية.", en: "Track every detail about your vehicles and equipment from start to finish." }, { ar: "مراقبة طلبات الصيانة وتتبعها.", en: "Monitor and track maintenance requests." }, { ar: "تبسيط جمع بيانات الوقود ومتابعة تكاليف الاستهلاك.", en: "Simplify fuel data collection and understand fuel costs." }, { ar: "السيطرة على المعدات والأدوات الصغيرة من أي مكان.", en: "Maintain control of small equipment and tools from anywhere." }, { ar: "تخطيط أوامر التشغيل وجدولة المهام وتتبع تكاليف الخدمة.", en: "Plan and schedule work orders, tasks, and service costs." }, { ar: "تتبع كميات قطع الغيار وتسجيل استخدامها وصلاحيتها.", en: "Track spare-part quantities, usage, and service life." }, { ar: "تنبيهات انتهاء رخص المركبات والسائقين ومواعيد الزيوت.", en: "Get vehicle and driver licence expiry and oil-change alerts." }, { ar: "فهم التكلفة الحقيقية لتشغيل أسطولك.", en: "Understand the true cost of operating your fleet." }],
    advantages: [{ ar: "قاعدة بيانات SQL على شبكة داخلية مع إمكانية الربط عبر الإنترنت", en: "SQL database on an internal network, with internet connectivity" }, { ar: "صلاحيات محددة لكل مستخدم وتذكير بالمواعيد التي توشك على الانتهاء", en: "Per-user permissions and reminders for upcoming expirations" }, { ar: "استيراد بيانات السيارات والسائقين من Excel وتسجيل كل معاملة بالتفصيل", en: "Import vehicle and driver data from Excel and record every transaction" }, { ar: "دعم التقويمين الميلادي والهجري والنسخ الاحتياطي لقاعدة البيانات", en: "Gregorian and Hijri calendar support and database backups" }],
    screenshots: ["hpucbgidob", "bdnanpqgzk", "labgmmjdqe", "aadpjuzfhr", "wygflikrcm", "jwrtwcjgxd", "nfxoyfugds", "ijyinyfhdy", "bieximcpga"].map((id, i) => ({ label: { ar: `لقطة أسطولي ${String(i + 1).padStart(2, "0")}`, en: `Ostoli screenshot ${String(i + 1).padStart(2, "0")}` }, src: `/dt4it/products/fleet-shot-${String(i + 1).padStart(2, "0")}.png` })),
  },
  {
    slug: "tailor", name: { ar: "خياط", en: "Tailor" }, short: { ar: "إدارة محلات الخياطة", en: "Tailoring management" }, tint: "rose", symbol: "02",
    image: "/dt4it/products/tailor-shot-01.png", cardImage: "/dt4it/products/tailor-card.png",
    sections: [{ title: { ar: "التفصيل والخياطة", en: "Tailoring" }, text: { ar: "خزّن معلومات العملاء ومقاساتهم واسترجعها بنقرة واحدة عبر تقارير شاملة، مع إمكانية تخصيص حقول المقاسات وعرضها في شاشات حديثة.", en: "Store customer and measurement details and retrieve them through comprehensive reports, with customizable measurement fields." }, image: "/dt4it/products/tailor-detail.png" }, { title: { ar: "المخزون والفروع", en: "Inventory and branches" }, text: { ar: "يدعم النظام السحابي تعدد الفروع والمخازن ومشاركة بيانات العملاء ومقاساتهم بشكل لحظي.", en: "The cloud system supports multiple branches and stores, with customer and measurement data shared in real time." }, image: "/dt4it/products/tailor-branches.png" }],
    description: { ar: "برنامج خياط لإدارة محلات الخياطة الرجالية والنسائية والعسكرية والزي الموحد. يدير العملاء ومقاساتهم والمخزون والأقمشة والحسابات، ويدعم الفاتورة الإلكترونية.", en: "Tailor is a complete system for managing men's, women's, military, and uniform tailoring shops. Manage customers and measurements, inventory, fabrics, and accounts, with electronic invoicing support." },
    features: [{ ar: "شاشة للتفصيل", en: "Detail screen" }, { ar: "المخزون", en: "Inventory" }, { ar: "إضافة موظفين", en: "Add employees" }, { ar: "الفاتورة الإلكترونية", en: "Electronic invoice" }, { ar: "الإشعارات", en: "Notifications" }, { ar: "رسائل الجوال", en: "Mobile messages" }, { ar: "التقارير", en: "Reports" }, { ar: "التصميم والوضع المظلم", en: "Design and dark mode" }],
    featureDetails: [{ ar: "شاشة متكاملة لأخذ المقاسات ومعلومات العملاء مع الاحتفاظ بمقاساتهم السابقة.", en: "An integrated screen for customer details and measurements, preserving previous measurements." }, { ar: "معرفة أرصدة المخزون الحالية وتكلفتها.", en: "View current inventory balances and costs." }, { ar: "إضافة موظفين بمسميات مختلفة مثل خياط وبائع.", en: "Add employees with roles such as tailor and salesperson." }, { ar: "متوافق مع متطلبات هيئة الزكاة والضريبة والجمارك ويدعم طباعة QR.", en: "Supports e-invoicing and QR printing." }, { ar: "تنبيهات متنوعة للمخزون، بما فيها التنبيه عند بلوغ حد الطلب.", en: "Inventory alerts, including low-stock notifications." }, { ar: "إرسال رسائل للعملاء لإبلاغهم بحالة الثوب.", en: "Send customers updates about garment status." }, { ar: "تقارير لحالات الثياب والدخل والمصروفات والمخزون.", en: "Reports on garment status, income, expenses, and inventory." }, { ar: "تصميم بسيط مع دعم الوضع المظلم.", en: "Simple design with dark mode support." }],
    advantages: [{ ar: "نظام سحابي يدعم جميع الأجهزة", en: "Cloud system supporting all devices" }, { ar: "حفظ بيانات العملاء ومقاساتهم للرجوع إليها لاحقاً", en: "Save customer details and measurements for future reference" }, { ar: "تخصيص حقول شاشة التفصيل وإضافة الحقول أو حذفها", en: "Customize the tailoring screen fields" }, { ar: "دعم كامل للفوترة الإلكترونية", en: "Full electronic invoicing support" }, { ar: "فروع ومخازن متعددة ومشاركة بيانات العملاء لحظياً", en: "Multiple branches and stores with real-time shared customer data" }],
    screenshots: ["iglnsnemtc", "ynbjtdfwys", "laxnftqsqn", "kdoxknkejy", "nydmkipnzc", "yrqgfryekc", "xhahqylfwa", "gjdxcanojm", "oijqoxnjnm"].map((id, i) => ({ label: { ar: `لقطة خياط ${String(i + 1).padStart(2, "0")}`, en: `Tailor screenshot ${String(i + 1).padStart(2, "0")}` }, src: `/dt4it/products/tailor-shot-${String(i + 1).padStart(2, "0")}.png` })),
    pricing: [{ name: { ar: "الباقة الذهبية", en: "Golden Package" }, price: "1199", oldPrice: "1899", discount: { ar: "خصم 37%", en: "37% OFF" }, period: { ar: "سنوياً", en: "Monthly" }, features: [{ ar: "الفروع", en: "Branch count" }, { ar: "يدعم الأجهزة المحمولة", en: "Mobile devices" }, { ar: "التنبيهات بالرسائل النصية", en: "SMS alerts" }, { ar: "الفاتورة الإلكترونية", en: "E-invoicing" }, { ar: "تعدد الفروع", en: "Multiple branches" }, { ar: "مناسب لجميع محلات الخياطة", en: "All tailors" }, { ar: "المخازن والصناديق", en: "Stores and cash boxes" }, { ar: "مبيعات الأصناف", en: "Item sales" }, { ar: "المصروفات", en: "Expenses" }] }],
  },
  {
    slug: "check", name: { ar: "الشيك الماسي", en: "Diamond Check" }, short: { ar: "إدارة وطباعة الشيكات", en: "Check management" }, tint: "blue", symbol: "03",
    image: "/dt4it/products/check-banner.png", cardImage: "/dt4it/products/check-card.png",
    sections: [{ title: { ar: "تصميم الشيكات", en: "Check design" }, text: { ar: "أداة مرنة لتصميم الشيكات وإدراج صورة الشيك بعد مسحها ضوئياً.", en: "A flexible check-design tool lets you insert a scanned image of the check." }, image: "/dt4it/products/check-design.png" }, { title: { ar: "تحرير وطباعة الشيكات", en: "Edit and print checks" }, text: { ar: "حرّر الشيكات واطبعها بأمر واحد دون الحاجة إلى طباعة كل شيك على حدة.", en: "Edit and print checks in one action instead of printing each one separately." }, image: "/dt4it/products/check-print.png" }, { title: { ar: "الحوالات", en: "Transfers" }, text: { ar: "صمّم قوالب الحوالات واطبعها باستخدام الطابعة النقطية بأصل وعدة نسخ.", en: "Design transfer templates and print originals with multiple copies using a dot-matrix printer." }, image: "/dt4it/products/check-transfers.png" }],
    description: { ar: "الشيك الماسي لإدارة وطباعة الشيكات المالية والحوالات. برنامج رائد وسهل الاستخدام، تستخدمه منشآت حكومية وخاصة لإدارة الشيكات والحوالات.", en: "Diamond Check manages and prints financial checks and transfers. A powerful, easy-to-use program trusted by government and private organizations." },
    features: [{ ar: "تصميم الشيكات", en: "Check design" }, { ar: "تحرير وطباعة الشيكات", en: "Edit and print checks" }, { ar: "الحوالات", en: "Transfers" }, { ar: "الإضافات", en: "Extras" }, { ar: "التذكير", en: "Reminders" }, { ar: "شاشة المطبوعات", en: "Printed checks" }, { ar: "الطابعة النقطية", en: "Dot-matrix printer" }, { ar: "التقارير", en: "Reports" }],
    featureDetails: [{ ar: "إدراج صورة الشيك بعد مسحها ضوئياً وتصميم حقولها بمرونة.", en: "Insert a scanned check image and design its fields flexibly." }, { ar: "تحرير الشيكات وطباعتها بأمر واحد بدلاً من طباعة كل شيك منفرداً.", en: "Edit and print checks in one action instead of individually." }, { ar: "تصميم قوالب الحوالات ودعم الطباعة النقطية بالأصل وعدة نسخ.", en: "Design transfer templates and print originals with multiple copies." }, { ar: "إضافة التاريخين الهجري والميلادي وبيانات المستفيد وحقول مخصصة.", en: "Add Hijri and Gregorian dates, beneficiary details, and custom fields." }, { ar: "التذكير بمواعيد الشيكات الدورية.", en: "Reminders for recurring check dates." }, { ar: "استعراض الشيكات المطبوعة وفرزها وترتيبها.", en: "View, sort, and organize printed checks." }, { ar: "طباعة الحوالات بأصل وعدة نسخ.", en: "Print transfers with an original and multiple copies." }, { ar: "تقارير الشيكات المحررة والمطبوعة والملغاة والحوالات.", en: "Reports for written, printed, and cancelled checks and transfers." }],
    advantages: [{ ar: "قواعد بيانات SQL وفروع بشيكات مستقلة", en: "SQL databases and independent checks for each branch" }, { ar: "إدارة المستفيدين والموظفين وكشوف الشيكات", en: "Manage beneficiaries, employees, and check statements" }, { ar: "حسابات المراقبة والإجماليات (الأستاذ العام)", en: "Control accounts and totals (general ledger)" }, { ar: "استيراد الموظفين والمستفيدين من Excel وطباعة الرواتب مجمعة", en: "Import employees and beneficiaries from Excel and print payroll checks in batches" }, { ar: "شبكة داخلية مع إمكانية الربط عبر الإنترنت", en: "Internal network with internet connectivity" }, { ar: "صلاحيات مستخدمين ونسخ احتياطي واستعادة تلقائية", en: "User permissions, backups, and automatic restore" }, { ar: "بحث شامل ودعم التاريخين الهجري والميلادي", en: "Global search and Hijri/Gregorian dates" }, { ar: "تصدير PDF وXLS وDOC", en: "Export PDF, XLS, and DOC reports" }],
    screenshots: ["hodwpbycwq.jpg", "pftgmdxjzs.png", "swotrcyolt.png", "ghzlbemxyt.jpg", "grajaieybp.png", "mseaorwjzj.png", "tznojufmqa.png", "qndgxjshrk.png", "sxylwyjmjx.jpg", "puwfydrbbt.jpg", "hoqdmkrnhs.png", "ttflzlarrn.png", "qgofkyjzuo.png"].map((file, i) => ({ label: { ar: `لقطة الشيك الماسي ${String(i + 1).padStart(2, "0")}`, en: `Diamond Check screenshot ${String(i + 1).padStart(2, "0")}` }, src: `/dt4it/products/check-shot-${String(i + 1).padStart(2, "0")}.${file.endsWith("jpg") ? "jpg" : "png"}` })),
    pricing: [{ name: { ar: "شيكات", en: "Cheque" }, price: "1350", oldPrice: "1350", discount: { ar: "خصم 0%", en: "0% OFF" }, period: { ar: "دفعة واحدة", en: "One-time payment" }, features: [{ ar: "يدعم نظام ويندوز", en: "Windows OS" }, { ar: "حفظ المستفيدين", en: "Save beneficiaries" }, { ar: "طباعة سند صرف مع الشيك", en: "Print payment voucher" }, { ar: "تقارير متنوعة", en: "Reports" }, { ar: "طباعة متعددة للشيكات", en: "Batch check printing" }] }, { name: { ar: "شيكات وحوالات", en: "Checks and transfers" }, price: "1650", oldPrice: "1650", discount: { ar: "خصم 0%", en: "0% OFF" }, period: { ar: "دفعة واحدة", en: "One-time payment" }, features: [{ ar: "يدعم نظام ويندوز", en: "Windows OS" }, { ar: "حفظ المستفيدين", en: "Save beneficiaries" }, { ar: "طباعة سند صرف مع الشيك", en: "Print payment voucher" }, { ar: "تقارير متنوعة", en: "Reports" }, { ar: "طباعة متعددة للشيكات", en: "Batch check printing" }, { ar: "طباعة الحوالات", en: "Transfer printing" }] }],
  },
  {
    slug: "archive", name: { ar: "الأرشيف الماسي", en: "Diamond Archive" }, short: { ar: "الأرشفة الإلكترونية", en: "Document archiving" }, tint: "green", symbol: "04",
    image: "/dt4it/products/archive-section1.png", cardImage: "/dt4it/products/archive-card.png",
    sections: [{ title: { ar: "إدارة الوثائق إلكترونياً", en: "Electronic document management" }, text: { ar: "أنشئ مشاريع مستقلة بمجموعاتها ومستخدميها وصلاحياتها وقوالبها، وأرشف الصور والمستندات مع إمكانات المسح الضوئي والبحث ومعالجة الصور.", en: "Create independent projects with their own groups, users, permissions, and templates. Archive images and documents with scanning, search, and image-processing tools." }, image: "/dt4it/products/archive-section2.png" }],
    description: { ar: "الأرشيف الماسي لتخزين وثائقك ومستنداتك بطريقة إلكترونية كاملة، مع إمكانية التحكم الكامل بالنظام.", en: "Diamond Archive stores your documents electronically and gives you full control of the system." },
    features: [{ ar: "المشاريع", en: "Projects" }, { ar: "الخانات", en: "Custom fields" }, { ar: "التذكير", en: "Reminders" }, { ar: "شاشة المطبوعات", en: "Prints screen" }, { ar: "الطابعة النقطية", en: "Dot-matrix printer" }, { ar: "التقارير", en: "Reports" }],
    featureDetails: [{ ar: "إنشاء عدد غير محدود من المشاريع بمجموعات ومستخدمين وصلاحيات وقوالب وبيانات مستقلة.", en: "Create unlimited projects with independent groups, users, permissions, templates, and data." }, { ar: "أنواع متعددة من الخانات: أرقام، نصوص، قوائم، تواريخ هجرية وميلادية، وخيارات منطقية.", en: "Use number, text, list, Hijri/Gregorian date, and boolean fields." }, { ar: "تنبيهات دورية لمواعيد الاستحقاق.", en: "Set reminders for recurring due dates." }, { ar: "استعراض العناصر المطبوعة مع إمكانية الفرز والترتيب.", en: "View, sort, and organize printed records." }, { ar: "دعم الطباعة النقطية للمستندات متعددة النسخ.", en: "Support dot-matrix printing for multi-copy documents." }, { ar: "تقارير للمستندات المسجلة والمطبوعة والملغاة.", en: "Reports for recorded, printed, and cancelled documents." }],
    advantages: [{ ar: "قواعد بيانات SQL Server ويعمل عبر الويب دون تثبيت على كل جهاز", en: "SQL Server and web access without installing on every device" }, { ar: "يعمل على شبكة محلية أو عالمية", en: "Runs on local or wide-area networks" }, { ar: "مشاريع متعددة ببيانات مستقلة", en: "Multiple projects with independent data" }, { ar: "أرشفة الصور والمستندات: JPEG وGIF وTIFF وWord وExcel وPDF", en: "Archive JPEG, GIF, TIFF, Word, Excel, and PDF files" }, { ar: "نظام متكامل للمستخدمين والصلاحيات ونسخ احتياطي للبيانات", en: "Integrated user permissions and data backups" }, { ar: "دعم أكواد الباركود والمسح الضوئي المباشر", en: "Barcode support and direct scanning" }, { ar: "معالجة الصور من حيث الإضاءة والتباين والألوان", en: "Image controls for brightness, contrast, and color" }],
    screenshots: ["isaybuqzfj", "ngzplrysue", "dgpgircfyq", "lgnxqyszmy", "rmhghcqwfb", "cxepbcdjjn", "ecnfedmusx", "tcbiokbhmc", "okufdggyax", "oetnqmmkaw"].map((id, i) => ({ label: { ar: `لقطة الأرشيف ${String(i + 1).padStart(2, "0")}`, en: `Archive screenshot ${String(i + 1).padStart(2, "0")}` }, src: `/dt4it/products/archive-shot-${String(i + 1).padStart(2, "0")}.png` })),
  },
];

const slides: { title: Copy; text: Copy; image: string; product?: string }[] = [
  { title: { ar: "دعم كامل", en: "Full support" }, text: { ar: "مع التكنولوجيا الماسية احلم بموقعك لأبعد الحدود ونحن نجعله لك واقعاً بأحدث تقنيات WEB2.0.", en: "With Diamond Technology, dream for your site beyond WEB2.0 frontiers and we make it a reality with the latest technologies." }, image: "/dt4it/home/slide-support.png" },
  { title: { ar: "تطبيق أسطولي", en: "Ostoli" }, text: { ar: "البرنامج المتكامل لإدارة السيارات والسائقين.", en: "The integrated program for managing cars and drivers." }, image: "/dt4it/home/slide-fleet.png", product: "fleet" },
  { title: { ar: "تطبيق الخياط", en: "Tailor" }, text: { ar: "لإدارة محلات الخياطة وفروعها باحترافية إلكترونياً، مع دعم الفاتورة الإلكترونية.", en: "Manage tailoring shops and branches professionally, with electronic invoicing support." }, image: "/dt4it/home/slide-tailor.png", product: "tailor" },
  { title: { ar: "أنظمة محاسبية", en: "Accounting systems" }, text: { ar: "حلول الفاتورة الإلكترونية المتوافقة مع أنظمة الزكاة والضريبة.", en: "Electronic invoicing solutions compatible with zakat and tax regulations." }, image: "/dt4it/home/slide-accounting.png" },
];

const services: { title: Copy; text: Copy; number: string; image: string }[] = [
  { number: "01", title: { ar: "تطبيقات الجوال", en: "Mobile applications" }, text: { ar: "نقدم مجموعة من الحلول المتقدمة وبأحدث التقنيات لتطوير تطبيقات الجوال.", en: "We offer advanced solutions and the latest technologies for developing mobile applications." }, image: "/dt4it/home/work1.png" },
  { number: "02", title: { ar: "تطوير الموقع", en: "Website development" }, text: { ar: "باستخدام أحدث التقنيات والتصاميم، نبني لك موقعك ليكون بوابتك إلى عالم الإنترنت.", en: "Using the latest technologies and designs, we build your website as a gateway to the online world." }, image: "/dt4it/home/work2.png" },
  { number: "03", title: { ar: "الأرشفة", en: "Archives" }, text: { ar: "نقوم بأرشفة مستنداتك عبر فريق مختص مهما كان حجمها وحالتها.", en: "We archive your documents through a specialized team, whatever their size or condition." }, image: "/dt4it/home/work3.png" },
  { number: "04", title: { ar: "الحلول والأنظمة", en: "Solutions and systems" }, text: { ar: "مجموعة من الحلول الذكية والنظم الإلكترونية لتطوير المنشآت والجهات الحكومية.", en: "Smart solutions and electronic systems to develop businesses and government agencies." }, image: "/dt4it/home/work4.png" },
];

const customers = ["زيدان للخياطة الرجالية", "متقن للخياطة الرجالية", "مخملي للخياطة الرجالية", "البويات والصناعات الكيماوية - باكين", "Dream 2000", "إميرالد للتطوير التعليمي وادارة المدارس", "الجمعية الفقهية السعودية", "أبن سعيدان العقارية", "الهرم الرقمي", "وزارة الشئون الإجتماعية بالرياض", "النادي الأدبي بالرياض", "مصنع شهية للحوم", "مجمع الموسى لتعليم القرآن الكريم", "معهد الأمير سلمان للتدريب", "مدينة الملك سعود الطبية", "وزارة الصحة", "جامعة الدمام", "جمعية الكشافة العربية السعودية", "وزارة التربية والتعليم", "الهيئة العربية لخدمات نقل الدم", "جامعة الملك سعود - كرسي الأبحاث", "مركز بصائر المستقبل للتدريب", "مدارس الصديق لتحفيظ القرآن", "شركة خالد علي التركي وأولاده", "شركة مجموعة الظاهري الدولية", "مصنع زنكو غراف جدة - فرع الرياض", "شركة مجموعة النصبان للصيانة والتشغيل", "شركة أبناء محمد أحمد العمير", "شركة مجموعة القاضي القابضة", "مؤسسة جونسون للعازل الحراري", "مؤسسة المدني", "مؤسسة الماجشون", "بن طالب للسباكة", "وزارة التربية والتعليم - مكتب نائب الرئيس", "معرض البراشي للسيارات", "شركة أجيال الرياض", "مجموعة العضيب", "مصنع جدف", "شركة آداك القابضة", "المجموعة السعودية للخدمات البيئية", "شركة السن المميز لطب الأسنان", "مؤسسة عالم التميز", "شركة محمد الحبيب القابضة", "شركة سواك المسلم", "مستوصف الأمل", "ميزان البلاد", "مؤسسة يوسف مرون للمقاولات", "مؤسسة على كيفك للتجارة", "مجموعة إدكس القابضة", "شركة الاختيار الأول للملاعب الرياضية", "شركة طنة المتحدة", "مؤسسة الفلم الشفاف (جونسون للعازل الحراري)", "مختبر الخلية المتقدم للتحاليل الطبية", "الهيئة الوطنية لمكافحة الفساد", "مؤسسة التسويق الوطنية", "شركة الدعائم العربية", "الشركة العربية للمقاولات الفنية (آرتك)", "قوات الأمن الخاصة", "شركة مصنع الصفوف الوطنية", "شركة رغس الدولية للمقاولات", "شركة مجمع إيبالا لطب وتقويم وزراعة الأسنان", "مكتب فوزان مشرف المشرف للاستقدام", "مؤسسة نستر للتجارة", "العربية لدعم وتأهيل المباني", "شركة التسويق المتحدة - يومارك", "شركة آد للهندسة", "مؤسسة ماجد مرشد الحربي لتأجير المعدات الثقيلة", "صالح الرشيد", "مزايا مول - المدينة المنورة", "مصنع أحلام الشرق للألمنيوم", "مؤسسة إيجاز المشاريع للمقاولات", "شركة أبو الجدايل للمقاولات", "شركة النايفات للتقسيط", "دار المشاغل", "شركة نبعة", "شركة منتجات الأحبار", "مصانع نجد للطوب الفخاري", "مؤسسة إعمار الجنوب للمقاولات", "سعودي سيليكون", "مؤسسة هات الدولية للنقل والترحيل (هتكس)", "شركة حلويات سعد الدين", "دار العاديات للنقل المدرسي", "الشركة الإلكترونية الحديثة", "مصنع نخيل الوطن للتمور", "شركة الراشد - أيه بيتونج", "خياط الرجل الفريد", "المركز الراقي للخياطة الرجالية", "شركة سايت تكنولوجي", "شركة موسى إبراهيم الكلثم وأولاده للتجارة", "أكاديمية نايف للأمن الوطني - مركز التدريب الوطني بالشرقية", "مجموعة النصبان", "شركة عبدالله سعيد السيد للمقاولات", "شركة سمنان للتجارة والصيانة القابضة", "شركة العبد اللطيف للمفروشات", "شركة الشملاني الدولية المحدودة", "شركة رضا الوطنية للدهانات وسلامة الطرق", "مؤسسة دراز للخياطة الرجالية", "شركة مصنع السعودية للرخام والجرانيت", "مركز أشياخ للخياطة", "شركة مفاد التجارية (كون زون)", "رابطة الأدب الإسلامي العالمية", "م/ علاء", "حمود سالم الزيد", "أ. يوسف علي الدوسري"];
const t = (copy: Copy, locale: Locale) => copy[locale];
const isRtl = (locale: Locale) => locale === "ar";

function useSiteLocale() {
  const location = useLocation();
  const navigate = useNavigate();
  const locale: Locale = new URLSearchParams(location.search).get("lang") === "en" ? "en" : "ar";
  useEffect(() => {
    document.documentElement.lang = locale;
    document.documentElement.dir = isRtl(locale) ? "rtl" : "ltr";
  }, [locale]);
  const toggle = () => {
    const params = new URLSearchParams(location.search);
    if (locale === "ar") params.set("lang", "en"); else params.delete("lang");
    navigate(`${location.pathname}${params.size ? `?${params.toString()}` : ""}`);
  };
  return { locale, toggle };
}

function Header({ locale, toggle, product }: { locale: Locale; toggle: () => void; product?: Product }) {
  const [menuOpen, setMenuOpen] = useState(false);
  const [productsOpen, setProductsOpen] = useState(false);
  const location = useLocation();
  const isArabic = isRtl(locale);
  const close = () => { setMenuOpen(false); setProductsOpen(false); };
  useEffect(() => { setMenuOpen(false); setProductsOpen(false); }, [location.pathname]);
  useEffect(() => {
    if (!menuOpen && !productsOpen) return;
    const onKey = (event: KeyboardEvent) => { if (event.key === "Escape") close(); };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [menuOpen, productsOpen]);
  const links = product
    ? [{ href: "#product-about", label: isArabic ? "عن المنتج" : "Overview" }, { href: "#features", label: isArabic ? "المزايا" : "Features" }, { href: "#screenshots", label: isArabic ? "لقطات النظام" : "Screenshots" }, { href: "#contact", label: t(words.nav.contact, locale) }]
    : [{ href: "#products", label: t(words.nav.products, locale) }, { href: "#services", label: t(words.nav.services, locale) }, { href: "#about", label: t(words.nav.about, locale) }, { href: "#contact", label: t(words.nav.contact, locale) }];
  return <header className="dt-header"><div className="dt-header-inner">
    <Link className="dt-brand" to={`/${location.search}`} onClick={close} aria-label="Diamond Technology home"><img className="dt-brand-logo" src="/dt4it/home/logo-en.png" alt="Diamond Technology" /></Link>
    <nav className={`dt-nav ${menuOpen ? "is-open" : ""}`} aria-label={isArabic ? "التنقل الرئيسي" : "Main navigation"}>
      {links.map((link) => <a key={link.href} href={link.href} onClick={close}>{link.label}</a>)}
      <div className={`dt-nav-products ${productsOpen ? "is-open" : ""}`}><button className="dt-nav-product-button" aria-expanded={productsOpen} onClick={() => setProductsOpen(!productsOpen)}>{isArabic ? "التطبيقات" : "Applications"}<IconChevronDown size={15} stroke={1.8} aria-hidden="true" /></button><div className="dt-products-menu">{products.map((item) => <Link key={item.slug} to={`/products/${item.slug}${location.search}`} onClick={close}>{t(item.name, locale)}<span>{t(item.short, locale)}</span></Link>)}</div></div>
      <button className="dt-lang" onClick={() => { toggle(); close(); }} aria-label={isArabic ? "Switch to English" : "التبديل إلى العربية"}>{isArabic ? "EN" : "عربي"}</button>
      <a className="dt-header-cta" href={product ? "#contact" : "#products"} onClick={close}>{product ? t(words.demo, locale) : t(words.nav.explore, locale)}<span aria-hidden="true"><IconArrowUpRight size={15} stroke={1.8} aria-hidden="true" /></span></a>
    </nav>
    <button className="dt-menu-toggle" onClick={() => setMenuOpen(!menuOpen)} aria-label={menuOpen ? (isArabic ? "إغلاق القائمة" : "Close menu") : (isArabic ? "فتح القائمة" : "Open menu")} aria-expanded={menuOpen}>{menuOpen ? <IconX size={21} stroke={1.8} aria-hidden="true" /> : <IconMenu2 size={21} stroke={1.8} aria-hidden="true" />}</button>
  </div></header>;
}

function ProductArt({ product, compact = false }: { product: Product; compact?: boolean }) {
  return <div className={`dt-product-art ${product.tint} ${compact ? "compact" : ""}`} aria-label={t(product.short, "en")} role="img">
    <img src={compact ? product.cardImage : product.image} alt="" loading="lazy" />
  </div>;
}

function Footer({ locale }: { locale: Locale }) {
  return <footer className="dt-footer"><div className="dt-container dt-footer-main"><div className="dt-footer-brand"><Link className="dt-brand" to={`/${locale === "en" ? "?lang=en" : ""}`} aria-label="Diamond Technology home"><img className="dt-footer-logo" src="/dt4it/home/logo-light.png" alt="Diamond Technology" /></Link><p>{t(words.footer, locale)}</p></div><div><h3>{t(words.nav.products, locale)}</h3>{products.map((p) => <Link key={p.slug} to={`/products/${p.slug}${locale === "en" ? "?lang=en" : ""}`}>{t(p.name, locale)}</Link>)}</div><div><h3>{t(words.nav.services, locale)}</h3>{services.map((s) => <a key={s.number} href="/#services">{t(s.title, locale)}</a>)}</div><div><h3>{t(words.nav.contact, locale)}</h3><a href="tel:920003556">920003556</a><a href="tel:0541126122">0541126122 / 0500892298</a><a href="tel:01066700599">01066700599 / 01022609925</a><a href="mailto:so@dt4it.com">so@dt4it.com</a><span>{locale === "ar" ? "المملكة العربية السعودية - الرياض" : "Saudi Arabia - Riyadh"}</span></div></div><div className="dt-container dt-footer-bottom"><span>{locale === "ar" ? "التكنولوجيا الماسية لتقنية المعلومات" : "Diamond Technology Co"} · {locale === "ar" ? "كل الحقوق محفوظة" : "All Rights Reserved"} © 2026</span><a href="https://wa.me/966500892298" target="_blank" rel="noreferrer">WhatsApp <IconArrowUpRight size={15} stroke={1.8} aria-hidden="true" /></a></div></footer>;
}

function Contact({ locale }: { locale: Locale }) {
  const [sent, setSent] = useState(false);
  const onSubmit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSent(true); };
  const isArabic = isRtl(locale);
  return <section className="dt-contact" id="contact"><div className="dt-container dt-contact-layout"><div className="dt-contact-copy"><span className="dt-kicker">{isArabic ? "نحن هنا لمساعدتك" : "WE’RE HERE TO HELP"}</span><h2>{t(words.contactTitle, locale)}</h2><p>{t(words.contactText, locale)}</p><a href="tel:920003556">920003556</a><a href="tel:0541126122">0541126122 / 0500892298</a><a href="tel:01066700599">01066700599 / 01022609925</a><a href="mailto:so@dt4it.com">so@dt4it.com</a><span>{isArabic ? "المملكة العربية السعودية - الرياض" : "Saudi Arabia - Riyadh"}</span></div><form className="dt-contact-form" onSubmit={onSubmit} onReset={() => setSent(false)}>{sent ? <div className="dt-form-success" role="status"><span><IconCheck size={20} stroke={2} aria-hidden="true" /></span><h3>{t(words.success, locale)}</h3><button type="reset" className="dt-text-button">{isArabic ? "إرسال رسالة أخرى" : "Send another message"}</button></div> : <><div className="dt-form-grid"><label>{isArabic ? "الاسم" : "Name"}<input name="name" autoComplete="name" required minLength={2} /></label><label>{isArabic ? "اسم الشركة" : "Company Name"}<input name="company" autoComplete="organization" /></label><label>{isArabic ? "البريد الإلكتروني" : "Email"}<input type="email" name="email" autoComplete="email" required /></label><label>{isArabic ? "رقم الهاتف" : "Phone"}<input type="tel" name="phone" autoComplete="tel" placeholder="05xxxxxxxx" required minLength={7} /></label></div><label>{isArabic ? "الرسالة" : "Message"}<textarea name="message" rows={4} required minLength={10} /></label><button className="dt-button dt-button-dark" type="submit">{t(words.send, locale)}<span aria-hidden="true"><IconArrowUpRight size={15} stroke={1.8} aria-hidden="true" /></span></button></>}</form></div></section>;
}

export function HomeExperience() {
  const { locale, toggle } = useSiteLocale();
  const isArabic = isRtl(locale);
  const [activeSlide, setActiveSlide] = useState(0);
  const heroSlide = slides[activeSlide];
  return <div className="dt-site" dir={isArabic ? "rtl" : "ltr"}><Header locale={locale} toggle={toggle} />
    <section className="dt-hero"><div className="dt-hero-grid" /><div className="dt-container dt-hero-layout"><div className="dt-hero-copy"><span className="dt-kicker"><i /> {isArabic ? "شركة التكنولوجيا الماسية" : "DIAMOND TECHNOLOGY COMPANY"}</span><h1>{t(heroSlide.title, locale)}</h1><p>{t(heroSlide.text, locale)}</p><div className="dt-hero-actions"><a className="dt-button dt-button-gold" href={heroSlide.product ? `/products/${heroSlide.product}${locale === "en" ? "?lang=en" : ""}` : "#products"}>{t(words.nav.explore, locale)}<span><IconArrowUpRight size={15} stroke={1.8} aria-hidden="true" /></span></a><a className="dt-button dt-button-outline" href="#about">{t(words.nav.about, locale)}</a></div><div className="dt-hero-proof"><b>{isArabic ? "15+" : "10+"}</b><span>{isArabic ? "عاماً من الخبرة في التقنية" : "years in business"}</span></div></div><div className="dt-hero-visual"><img className="dt-hero-slide-image" src={heroSlide.image} alt={t(heroSlide.title, locale)} /><div className="dt-slide-controls" aria-label={isArabic ? "اختيار العرض" : "Choose a featured slide"}>{slides.map((slide, index) => <button key={slide.title.en} onClick={() => setActiveSlide(index)} aria-label={t(slide.title, locale)} aria-pressed={activeSlide === index}>{String(index + 1).padStart(2, "0")}</button>)}</div></div></div><a className="dt-scroll-cue" href="#about">{isArabic ? "اكتشف المزيد" : "SCROLL TO EXPLORE"}<IconArrowDown size={15} stroke={1.8} aria-hidden="true" /></a></section>
    <section className="dt-about" id="about"><div className="dt-container dt-about-layout"><div><span className="dt-kicker">01 / {isArabic ? "من نحن" : "ABOUT US"}</span><h2>{t(words.aboutTitle, locale)}</h2></div><div className="dt-about-copy"><img className="dt-about-image" src="/dt4it/home/about.png" alt={isArabic ? "عن التكنولوجيا الماسية" : "About Diamond Technology"} loading="lazy" /><p>{t(words.aboutText, locale)}</p><a className="dt-inline-link" href="#services">{isArabic ? "تعرف على خدماتنا" : "Discover our services"}<span><IconArrowUpRight size={15} stroke={1.8} aria-hidden="true" /></span></a></div><div className="dt-about-rule"><span>DT4IT</span><span>SAUDI ARABIA · EST. 2009</span></div></div></section>
    <section className="dt-services" id="services"><div className="dt-container"><div className="dt-section-heading"><div><span className="dt-kicker">02 / {isArabic ? "خدماتنا" : "WHAT WE DO"}</span><h2>{t(words.servicesTitle, locale)}</h2></div><p>{isArabic ? "منصة تقنية واحدة، وخبرات تغطي مراحل التحول الرقمي." : "One technology partner for every stage of your digital journey."}</p></div><div className="dt-service-grid">{services.map((service) => <article key={service.number} className="dt-service-card"><span>{service.number}</span><img src={service.image} alt="" loading="lazy" /><h3>{t(service.title, locale)}</h3><p>{t(service.text, locale)}</p><a href="#contact" aria-label={`${t(service.title, locale)} — ${t(words.nav.contact, locale)}`}><IconArrowUpRight size={15} stroke={1.8} aria-hidden="true" /></a></article>)}</div></div></section>
    <section className="dt-products" id="products"><div className="dt-container"><div className="dt-section-heading"><div><span className="dt-kicker">03 / {isArabic ? "منتجاتنا" : "OUR PRODUCTS"}</span><h2>{t(words.productsTitle, locale)}</h2></div><p>{t(words.productsIntro, locale)}</p></div><div className="dt-product-grid">{products.map((product) => <article className="dt-product-card" key={product.slug}><Link className="dt-product-card-art" to={`/products/${product.slug}${locale === "en" ? "?lang=en" : ""}`} aria-label={`${t(words.more, locale)}: ${t(product.name, locale)}`}><ProductArt product={product} compact /></Link><div className="dt-product-card-meta"><span>{t(product.short, locale)}</span><span>{product.symbol}</span></div><h3><Link to={`/products/${product.slug}${locale === "en" ? "?lang=en" : ""}`}>{t(product.name, locale)}</Link></h3><p>{t(product.description, locale)}</p><Link className="dt-inline-link" to={`/products/${product.slug}${locale === "en" ? "?lang=en" : ""}`}>{t(words.more, locale)}<span><IconArrowUpRight size={15} stroke={1.8} aria-hidden="true" /></span></Link></article>)}</div></div></section>
    <section className="dt-clients" id="clients"><div className="dt-container"><div className="dt-section-heading"><div><span className="dt-kicker">04 / {isArabic ? "شركاء النجاح" : "OUR PARTNERS"}</span><h2>{t(words.clientsTitle, locale)}</h2></div><p>{t(words.clients, locale)}</p></div><div className="dt-client-grid">{customers.map((customer, i) => <div className="dt-client" key={customer}><span>{String(i + 1).padStart(2, "0")}</span><b>{customer}</b></div>)}</div></div></section>
    <Contact locale={locale} /><Footer locale={locale} />
    <a className="dt-whatsapp" href="https://wa.me/966500892298" target="_blank" rel="noreferrer" aria-label="Contact us on WhatsApp"><IconBrandWhatsapp size={24} stroke={1.8} aria-hidden="true" /></a>
  </div>;
}

function DemoDialog({ locale, product }: { locale: Locale; product: Product }) {
  const dialogRef = useRef<HTMLDialogElement>(null);
  const dialogTitleId = useId();
  const [sent, setSent] = useState(false);
  const isArabic = isRtl(locale);
  const close = () => { dialogRef.current?.close(); setSent(false); };
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSent(true); };
  return <><button className="dt-button dt-button-gold" onClick={() => dialogRef.current?.showModal()}>{t(words.demo, locale)}<span><IconArrowUpRight size={15} stroke={1.8} aria-hidden="true" /></span></button><dialog className="dt-dialog" ref={dialogRef} aria-labelledby={dialogTitleId} onClose={() => setSent(false)}><button className="dt-dialog-close" type="button" onClick={close} aria-label={isArabic ? "إغلاق" : "Close"}><IconX size={20} stroke={1.8} aria-hidden="true" /></button>{sent ? <div className="dt-form-success" role="status"><span><IconCheck size={20} stroke={2} aria-hidden="true" /></span><h2>{t(words.success, locale)}</h2><button className="dt-button dt-button-dark" onClick={close}>{isArabic ? "إغلاق" : "Close"}</button></div> : <><span className="dt-kicker">{t(product.name, locale)}</span><h2 id={dialogTitleId}>{t(words.demo, locale)}</h2><p>{isArabic ? "اترك بياناتك وسنتواصل معك لترتيب العرض." : "Leave your details and we’ll arrange a product walkthrough."}</p><form onSubmit={submit}><label>{isArabic ? "الاسم" : "Name"}<input required minLength={2} autoComplete="name" /></label><label>{isArabic ? "البريد الإلكتروني" : "Email"}<input type="email" required autoComplete="email" /></label><label>{isArabic ? "رقم الهاتف" : "Phone"}<input type="tel" required minLength={7} autoComplete="tel" placeholder="05xxxxxxxx" /></label><div className="dt-dialog-actions"><button className="dt-button dt-button-gold" type="submit">{t(words.demo, locale)}<span><IconArrowUpRight size={15} stroke={1.8} aria-hidden="true" /></span></button><button className="dt-text-button" type="button" onClick={close}>{isArabic ? "إلغاء" : "Cancel"}</button></div></form></>}</dialog></>;
}

export function ProductExperience() {
  const { locale, toggle } = useSiteLocale();
  const { slug } = useParams();
  const product = products.find((item) => item.slug === slug);
  const [activeShot, setActiveShot] = useState(0);
  const isArabic = isRtl(locale);
  if (!product) return <div className="dt-site" dir={isArabic ? "rtl" : "ltr"}><Header locale={locale} toggle={toggle} /><main className="dt-not-found"><span className="dt-kicker">404 / {isArabic ? "صفحة غير موجودة" : "PAGE NOT FOUND"}</span><h1>{isArabic ? "لم نعثر على هذا المنتج" : "We couldn’t find that product."}</h1><Link className="dt-button dt-button-gold" to={`/${locale === "en" ? "?lang=en" : ""}`}>{isArabic ? "العودة للرئيسية" : "Back to home"}</Link></main><Footer locale={locale} /></div>;
  return <div className="dt-site" dir={isArabic ? "rtl" : "ltr"}><Header locale={locale} toggle={toggle} product={product} />
    <section className={`dt-product-hero ${product.tint}`}><div className="dt-container dt-product-hero-layout"><div className="dt-product-intro"><Link className="dt-back-link" to={`/${locale === "en" ? "?lang=en" : ""}`}><IconArrowLeft size={15} aria-hidden="true" /> {isArabic ? "كل المنتجات" : "All products"}</Link><span className="dt-kicker">{t(product.short, locale)} / DT4IT</span><h1>{t(product.name, locale)}</h1><p>{t(product.description, locale)}</p><div className="dt-hero-actions"><DemoDialog locale={locale} product={product} /><a className="dt-button dt-button-outline" href="#features">{isArabic ? "استكشف المزايا" : "Explore features"}</a></div></div><ProductArt product={product} /></div></section>
    <section className="dt-product-overview" id="product-about"><div className="dt-container dt-overview-layout"><span className="dt-kicker">01 / {isArabic ? "نظرة عامة" : "OVERVIEW"}</span><h2>{isArabic ? <>كل التفاصيل،<br /><em>في مكان واحد.</em></> : <>Everything in view.<br /><em>All in one place.</em></>}</h2><p>{t(product.description, locale)} {isArabic ? "واجهة واضحة تجمع بياناتك وتساعد فريقك على اتخاذ قرارات أسرع." : "A clear workspace brings information together and helps your team make better decisions."}</p><div className="dt-overview-mark">{product.symbol}</div></div></section>
    <section className="dt-product-details"><div className="dt-container">{product.sections.map((section, index) => <article className="dt-product-detail-row" key={section.title.en}><div><span className="dt-kicker">{String(index + 1).padStart(2, "0")} / {t(section.title, locale)}</span><h2>{t(section.title, locale)}</h2><p>{t(section.text, locale)}</p></div>{section.image && <img src={section.image} alt={t(section.title, locale)} loading="lazy" />}</article>)}</div></section>
    <section className="dt-feature-section" id="features"><div className="dt-container"><div className="dt-section-heading"><div><span className="dt-kicker">02 / {isArabic ? "الخصائص" : "CAPABILITIES"}</span><h2>{t(words.featuresTitle, locale)}</h2></div></div><div className="dt-feature-grid">{product.features.map((feature, i) => <article className="dt-feature" key={feature.en}><span>{String(i + 1).padStart(2, "0")}</span><h3>{t(feature, locale)}</h3><p>{t(product.featureDetails[i], locale)}</p><i aria-hidden="true"><IconArrowUpRight size={15} stroke={1.8} aria-hidden="true" /></i></article>)}</div></div></section>
    <section className="dt-advantages"><div className="dt-container dt-advantages-layout"><div><span className="dt-kicker">03 / {isArabic ? "إمكانات النظام" : "SYSTEM ADVANTAGES"}</span><h2>{t(words.advantagesTitle, locale)}</h2></div><ul>{product.advantages.map((item) => <li key={item.en}><span><IconCheck size={16} stroke={2} aria-hidden="true" /></span>{t(item, locale)}</li>)}</ul></div></section>
    <section className="dt-gallery" id="screenshots"><div className="dt-container"><div className="dt-section-heading"><div><span className="dt-kicker">04 / {isArabic ? "معرض النظام" : "PRODUCT GALLERY"}</span><h2>{t(words.screenshotsTitle, locale)}</h2></div><div className="dt-gallery-controls"><button onClick={() => setActiveShot((activeShot + product.screenshots.length - 1) % product.screenshots.length)} aria-label={isArabic ? "الصورة السابقة" : "Previous screenshot"}><IconArrowLeft size={17} aria-hidden="true" /></button><button onClick={() => setActiveShot((activeShot + 1) % product.screenshots.length)} aria-label={isArabic ? "الصورة التالية" : "Next screenshot"}><IconArrowRight size={17} aria-hidden="true" /></button></div></div><div className="dt-gallery-layout"><div className="dt-gallery-main"><img className="dt-gallery-image" src={product.screenshots[activeShot].src} alt={t(product.screenshots[activeShot].label, locale)} /><span className="dt-gallery-label">{String(activeShot + 1).padStart(2, "0")} / {t(product.screenshots[activeShot].label, locale)}</span></div><div className="dt-gallery-thumbs" role="tablist" aria-label={t(words.screenshotsTitle, locale)}>{product.screenshots.map((shot, index) => <button className={activeShot === index ? "active" : ""} key={shot.src} role="tab" aria-selected={activeShot === index} onClick={() => setActiveShot(index)}><span>{String(index + 1).padStart(2, "0")}</span>{t(shot.label, locale)}</button>)}</div></div></div></section>
    {product.pricing && <section className="dt-pricing"><div className="dt-container"><div className="dt-section-heading"><div><span className="dt-kicker">05 / {isArabic ? "الباقات" : "PACKAGES"}</span><h2>{t(words.pricingTitle, locale)}</h2></div></div><div className="dt-pricing-cards">{product.pricing.map((plan) => <article className="dt-price-card" key={plan.name.en}><span>{t(plan.name, locale)}</span><div className="dt-price-value"><strong>{plan.price}</strong>{plan.oldPrice && <del>{plan.oldPrice}</del>}<small>{t(plan.period, locale)}</small>{plan.discount && <span className="dt-price-discount">{t(plan.discount, locale)}</span>}</div><ul>{plan.features.map((item) => <li key={item.en}><IconCheck size={16} aria-hidden="true" />{t(item, locale)}</li>)}</ul><DemoDialog locale={locale} product={product} /></article>)}</div></div></section>}
    <section className="dt-product-cta"><div className="dt-container"><span className="dt-kicker">{isArabic ? "خطوتك التالية" : "YOUR NEXT STEP"}</span><h2>{isArabic ? "اكتشف كيف يناسب هذا النظام أعمالك." : "See how this product fits your business."}</h2><DemoDialog locale={locale} product={product} /></div></section>
    <Contact locale={locale} /><Footer locale={locale} /><a className="dt-whatsapp" href="https://wa.me/966500892298" target="_blank" rel="noreferrer" aria-label="Contact us on WhatsApp"><IconBrandWhatsapp size={24} stroke={1.8} aria-hidden="true" /></a>
  </div>;
}
